
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package luban;


import "errors"

type ConstData struct {
    ManaMax int32
    ManaRegenRate float32
    InitialMana int32
}

const TypeId_ConstData = 1580814733

func (*ConstData) GetTypeId() int32 {
    return 1580814733
}

func NewConstData(_buf map[string]interface{}) (_v *ConstData, err error) {
    _v = &ConstData{}
    { var _ok_ bool; var __json_manaMax__ interface{}; if __json_manaMax__, _ok_ = _buf["manaMax"]; !_ok_ || __json_manaMax__ == nil { err = errors.New("manaMax error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_manaMax__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ManaMax = __x__ }}
    { var _ok_ bool; var __json_manaRegenRate__ interface{}; if __json_manaRegenRate__, _ok_ = _buf["manaRegenRate"]; !_ok_ || __json_manaRegenRate__ == nil { err = errors.New("manaRegenRate error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_manaRegenRate__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.ManaRegenRate = __x__ }}
    { var _ok_ bool; var __json_initialMana__ interface{}; if __json_initialMana__, _ok_ = _buf["initialMana"]; !_ok_ || __json_initialMana__ == nil { err = errors.New("initialMana error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_initialMana__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.InitialMana = __x__ }}
    return
}

