
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package luban;



import "errors"

type TbConstData struct {
    _data *ConstData
}

func NewTbConstData(_buf []map[string]interface{}) (*TbConstData, error) {
	if len(_buf) != 1 {
        return nil, errors.New(" size != 1 ")
	} else {
		if _v, err2 := NewConstData(_buf[0]); err2 != nil {
			return nil, err2
		} else {
		    return &TbConstData{_data:_v}, nil
		}
	}
}

func (table *TbConstData) Get() *ConstData {
    return table._data
}


