
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package luban;


type TbTowerData struct {
    _dataMap map[int32]*TowerData
    _dataList []*TowerData
}

func NewTbTowerData(_buf []map[string]interface{}) (*TbTowerData, error) {
    _dataList := make([]*TowerData, 0, len(_buf))
    dataMap := make(map[int32]*TowerData)

    for _, _ele_ := range _buf {
        if _v, err2 := NewTowerData(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbTowerData{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbTowerData) GetDataMap() map[int32]*TowerData {
    return table._dataMap
}

func (table *TbTowerData) GetDataList() []*TowerData {
    return table._dataList
}

func (table *TbTowerData) Get(key int32) *TowerData {
    return table._dataMap[key]
}


