
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package luban;


import "errors"

type TowerData struct {
    Id int32
    Name string
    HP int32
    ManaCost int32
    Invertal float32
    Damage int32
    Dps string
}

const TypeId_TowerData = -86196685

func (*TowerData) GetTypeId() int32 {
    return -86196685
}

func NewTowerData(_buf map[string]interface{}) (_v *TowerData, err error) {
    _v = &TowerData{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_HP__ interface{}; if __json_HP__, _ok_ = _buf["HP"]; !_ok_ || __json_HP__ == nil { err = errors.New("HP error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_HP__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.HP = __x__ }}
    { var _ok_ bool; var __json_manaCost__ interface{}; if __json_manaCost__, _ok_ = _buf["manaCost"]; !_ok_ || __json_manaCost__ == nil { err = errors.New("manaCost error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_manaCost__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ManaCost = __x__ }}
    { var _ok_ bool; var __json_invertal__ interface{}; if __json_invertal__, _ok_ = _buf["invertal"]; !_ok_ || __json_invertal__ == nil { err = errors.New("invertal error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_invertal__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Invertal = __x__ }}
    { var _ok_ bool; var __json_damage__ interface{}; if __json_damage__, _ok_ = _buf["damage"]; !_ok_ || __json_damage__ == nil { err = errors.New("damage error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_damage__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Damage = __x__ }}
    { var _ok_ bool; var __json_dps__ interface{}; if __json_dps__, _ok_ = _buf["dps"]; !_ok_ || __json_dps__ == nil { err = errors.New("dps error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_dps__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Dps = __x__ }}
    return
}

