
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;



public sealed partial class ConstData : Luban.BeanBase
{
    public ConstData(JSONNode _buf) 
    {
        { if(!_buf["manaMax"].IsNumber) { throw new SerializationException(); }  ManaMax = _buf["manaMax"]; }
        { if(!_buf["playerCellHP"].IsNumber) { throw new SerializationException(); }  PlayerCellHP = _buf["playerCellHP"]; }
        { if(!_buf["neutralCellHP"].IsNumber) { throw new SerializationException(); }  NeutralCellHP = _buf["neutralCellHP"]; }
    }

    public static ConstData DeserializeConstData(JSONNode _buf)
    {
        return new ConstData(_buf);
    }

    /// <summary>
    /// 最大圣水
    /// </summary>
    public readonly int ManaMax;
    public readonly int PlayerCellHP;
    public readonly int NeutralCellHP;
   
    public const int __ID__ = 1580814733;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "manaMax:" + ManaMax + ","
        + "playerCellHP:" + PlayerCellHP + ","
        + "neutralCellHP:" + NeutralCellHP + ","
        + "}";
    }
}


