
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


public partial class Tables
{
    public TbConstData TbConstData {get; }
    public TbTowerData TbTowerData {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbConstData = new TbConstData(loader("tbconstdata"));
        TbTowerData = new TbTowerData(loader("tbtowerdata"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbConstData.ResolveRef(this);
        TbTowerData.ResolveRef(this);
    }
}


