
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;



public partial class TbConstData
{

     private readonly ConstData _data;

     public ConstData Data => _data;

    public TbConstData(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = global::ConstData.DeserializeConstData(_buf[0]);  }
    }


    /// <summary>
    /// 最大圣水
    /// </summary>
     public int ManaMax => _data.ManaMax;
     public int PlayerCellHP => _data.PlayerCellHP;
     public int NeutralCellHP => _data.NeutralCellHP;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}



