
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;



public partial class TbTowerData
{
    private readonly System.Collections.Generic.Dictionary<int, TowerData> _dataMap;
    private readonly System.Collections.Generic.List<TowerData> _dataList;
    
    public TbTowerData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, TowerData>(count);
        _dataList = new System.Collections.Generic.List<TowerData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TowerData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::TowerData.DeserializeTowerData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TowerData> DataMap => _dataMap;
    public System.Collections.Generic.List<TowerData> DataList => _dataList;

    public TowerData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TowerData Get(int key) => _dataMap[key];
    public TowerData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



