
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;



public sealed partial class TowerData : Luban.BeanBase
{
    public TowerData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["HP"].IsNumber) { throw new SerializationException(); }  HP = _buf["HP"]; }
        { if(!_buf["manaCost"].IsNumber) { throw new SerializationException(); }  ManaCost = _buf["manaCost"]; }
        { if(!_buf["invertal"].IsNumber) { throw new SerializationException(); }  Invertal = _buf["invertal"]; }
        { if(!_buf["damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["damage"]; }
        { if(!_buf["dps"].IsString) { throw new SerializationException(); }  Dps = _buf["dps"]; }
    }

    public static TowerData DeserializeTowerData(JSONNode _buf)
    {
        return new TowerData(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly string Desc;
    public readonly int HP;
    public readonly int ManaCost;
    /// <summary>
    /// 行动间隔
    /// </summary>
    public readonly float Invertal;
    public readonly int Damage;
    /// <summary>
    /// num*damage /(manaCost*invertal) 1圣水1s造成的伤害
    /// </summary>
    public readonly string Dps;
   
    public const int __ID__ = -86196685;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "HP:" + HP + ","
        + "manaCost:" + ManaCost + ","
        + "invertal:" + Invertal + ","
        + "damage:" + Damage + ","
        + "dps:" + Dps + ","
        + "}";
    }
}


