
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



 
    public enum BondType
    {
        Attack = 0,
        Defend = 1,
        Move = 2,
        HP = 3,
    }

 

