
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;



public sealed partial class BondData : Luban.BeanBase
{
    public BondData(JSONNode _buf) 
    {
        { if(!_buf["bond"].IsNumber) { throw new SerializationException(); }  Bond = (BondType)_buf["bond"].AsInt; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["level"]; if(!__json0.IsArray) { throw new SerializationException(); } Level = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Level.Add(__v0); }   }
        { var __json0 = _buf["desc"]; if(!__json0.IsArray) { throw new SerializationException(); } Desc = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Desc.Add(__v0); }   }
    }

    public static BondData DeserializeBondData(JSONNode _buf)
    {
        return new BondData(_buf);
    }

    public readonly BondType Bond;
    public readonly string Name;
    public readonly System.Collections.Generic.List<int> Level;
    public readonly System.Collections.Generic.List<string> Desc;
   
    public const int __ID__ = 2033707309;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "bond:" + Bond + ","
        + "name:" + Name + ","
        + "level:" + Luban.StringUtil.CollectionToString(Level) + ","
        + "desc:" + Luban.StringUtil.CollectionToString(Desc) + ","
        + "}";
    }
}


