
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



 
    public enum BuffType
    {
        /// <summary>
        /// 永久加攻击
        /// </summary>
        Attack = 0,
        /// <summary>
        /// 永久加防御
        /// </summary>
        Defend = 1,
        /// <summary>
        /// 永久加移动
        /// </summary>
        Move = 2,
        /// <summary>
        /// 永久加血量
        /// </summary>
        MaxHP = 3,
        /// <summary>
        /// parma1=1 代表攻速度增加1%
        /// </summary>
        AttackInternal = 4,
    }

 

