
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;



public sealed partial class BuffData : Luban.BeanBase
{
    public BuffData(JSONNode _buf) 
    {
        { if(!_buf["useType"].IsNumber) { throw new SerializationException(); }  UseType = (BuffType)_buf["useType"].AsInt; }
        { if(!_buf["Param1"].IsNumber) { throw new SerializationException(); }  Param1 = _buf["Param1"]; }
        { if(!_buf["Param2"].IsNumber) { throw new SerializationException(); }  Param2 = _buf["Param2"]; }
    }

    public static BuffData DeserializeBuffData(JSONNode _buf)
    {
        return new BuffData(_buf);
    }

    /// <summary>
    /// 如何使用
    /// </summary>
    public readonly BuffType UseType;
    /// <summary>
    /// 值1
    /// </summary>
    public readonly int Param1;
    /// <summary>
    /// 值2
    /// </summary>
    public readonly int Param2;
   
    public const int __ID__ = -1458391363;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "useType:" + UseType + ","
        + "Param1:" + Param1 + ","
        + "Param2:" + Param2 + ","
        + "}";
    }
}


