
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;



public sealed partial class CharacterData : Luban.BeanBase
{
    public CharacterData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["characterType"].IsNumber) { throw new SerializationException(); }  CharacterType = (CharacterType)_buf["characterType"].AsInt; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["MaxHP"].IsNumber) { throw new SerializationException(); }  MaxHP = _buf["MaxHP"]; }
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
        { if(!_buf["defend"].IsNumber) { throw new SerializationException(); }  Defend = _buf["defend"]; }
        { if(!_buf["moveInterval"].IsNumber) { throw new SerializationException(); }  MoveInterval = _buf["moveInterval"]; }
        { if(!_buf["attackInterval"].IsNumber) { throw new SerializationException(); }  AttackInterval = _buf["attackInterval"]; }
        { if(!_buf["attackWindup"].IsNumber) { throw new SerializationException(); }  AttackWindup = _buf["attackWindup"]; }
        { if(!_buf["attackRange"].IsNumber) { throw new SerializationException(); }  AttackRange = _buf["attackRange"]; }
        { var __json0 = _buf["bondList"]; if(!__json0.IsArray) { throw new SerializationException(); } BondList = new System.Collections.Generic.List<BondType>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { BondType __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (BondType)__e0.AsInt; }  BondList.Add(__v0); }   }
    }

    public static CharacterData DeserializeCharacterData(JSONNode _buf)
    {
        return new CharacterData(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly CharacterType CharacterType;
    public readonly string Desc;
    public readonly int MaxHP;
    public readonly int Attack;
    public readonly int Defend;
    public readonly float MoveInterval;
    public readonly float AttackInterval;
    public readonly float AttackWindup;
    public readonly int AttackRange;
    public readonly System.Collections.Generic.List<BondType> BondList;
   
    public const int __ID__ = -991456685;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "characterType:" + CharacterType + ","
        + "desc:" + Desc + ","
        + "MaxHP:" + MaxHP + ","
        + "attack:" + Attack + ","
        + "defend:" + Defend + ","
        + "moveInterval:" + MoveInterval + ","
        + "attackInterval:" + AttackInterval + ","
        + "attackWindup:" + AttackWindup + ","
        + "attackRange:" + AttackRange + ","
        + "bondList:" + Luban.StringUtil.CollectionToString(BondList) + ","
        + "}";
    }
}


