
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


public partial class Tables
{
    public TbBondData TbBondData {get; }
    public TbCharacterData TbCharacterData {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbBondData = new TbBondData(loader("tbbonddata"));
        TbCharacterData = new TbCharacterData(loader("tbcharacterdata"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbBondData.ResolveRef(this);
        TbCharacterData.ResolveRef(this);
    }
}


