
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;



public partial class TbBondData
{
    private readonly System.Collections.Generic.Dictionary<BondType, BondData> _dataMap;
    private readonly System.Collections.Generic.List<BondData> _dataList;
    
    public TbBondData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<BondType, BondData>(count);
        _dataList = new System.Collections.Generic.List<BondData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BondData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::BondData.DeserializeBondData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Bond, _v);
        }
    }

    public System.Collections.Generic.Dictionary<BondType, BondData> DataMap => _dataMap;
    public System.Collections.Generic.List<BondData> DataList => _dataList;

    public BondData GetOrDefault(BondType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BondData Get(BondType key) => _dataMap[key];
    public BondData this[BondType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



